version: '3.7'

services:
  wordpress:
    build: .
    restart: always
    depends_on:
      - database
    volumes:
      - ./public:/var/www/html:cached
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/wordpress/wp-cli.local.yml:/var/www/html/wp-cli.local.yml
      - ./config/home/.bash_profile:/var/www/.bash_profile
      - ./logs/php:/var/log/php
      - ./logs/npm:/var/www/npm/_logs
      - ./config/mysql/my.cnf:/etc/my.cnf
      - ~/.ssh:/var/www/.ssh
    environment:
      WORDPRESS_DB_HOST: ${SERVICE_GROUP}_database
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    labels:
      - traefik.enable=false
    networks:
      - devcafe-internal
      - default
    container_name: ${SERVICE_GROUP}_wordpress

  database:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./data/db:/var/lib/mysql:delegated
      - ./config/mysql/my.cnf:/etc/my.cnf
      - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: mysqladmin ping -u${DB_USER} -p${DB_PASS} -hlocalhost || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - devcafe-internal
    labels:
      - traefik.enable=false
    container_name: ${SERVICE_GROUP}_database

  webserver:
    image: nginx:latest
    restart: always
    volumes:
      - ./public:/var/www/html:cached
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./logs/nginx:/var/log/nginx
      - ~/Personal/traefik-proxy/certs:/etc/ssl/
    depends_on:
      - wordpress
    environment:
      VIRTUAL_HOST: ${LOCAL_DOMAIN}
      FASTCGI_PASS: ${SERVICE_GROUP}_wordpress
    command: /bin/bash -c "envsubst '$$FASTCGI_PASS$$VIRTUAL_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.developercafe.test
      - traefik.port=80
      - traefik.docker.network=devcafe-docker_devcafe # this is the true name of the network - https://stackoverflow.com/questions/46161017/gateway-timeout-with-traefik-and-php-fpm
    networks:
      - default
      - devcafe-internal
    container_name: ${SERVICE_GROUP}_webserver

networks:
  default:
    external:
      name: gateway

  devcafe-internal:
    internal: true
